#category_count:
#  cron: "* */1 * * *"
#  class: "CategoryWorker"

fetch_pages:
  cron: "*/20 * * * *"
  class: "FetchingWorker"

tweets:
  cron: "*/30 * * * *"
  class: "FetchingTweetsWorker"

category_count:
  cron: "* */6 * * *"
  class: "CategoryWorker"

tags_pages:
  cron: "*/15 * * * *"
  class: "TagsWorker"
