fetch_pages:
  cron: "*/20 * * * *"
  class: "FetchingWorker"

tweets:
  cron: "*/30 * * * *"
  class: "FetchingTweetsWorker"

category_count:
  cron: "* */6 * * *"
  class: "CategoryWorker"

tags_pages:
  cron: "*/15 * * * *"
  class: "TagsWorker"

categories_delete:
  cron: "* */4 * * *"
  class: "CategoryDeleteWorker"

infos:
  cron: "* */12 * * *"
  class: "InfodayWorker"